kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Name}}-role
rules:
- appiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - "extensions"
  - "apps"
  resource:
  - deployments
  - pods
  verbs:
  - '*'