name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'base-helm-charts/deplorch/**' # Trigger only on changes to chart source files

jobs:
  release:
    permissions:
      contents: write # Required to create releases and update gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for chart-releaser to determine changes

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0 # Use the latest version
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # Optional: CR_CONFIG: cr.yaml # if you need a custom config
